language: java
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.cache"

jobs:
  - stage: deploy
    name: "Deploy To Dev Environment"
    script: 
      - mvn clean install
      - cp .travis.settings.xml $HOME/.m2/settings.xml
      - mvn deploy -DmuleDeploy -Dserver=$server -Dworkers=%$workers -DworkerType=$workerType -Denvironment=$environment -DmuleVersion=$muleversion -DappName=$appName
    if: branch = dev